---

- include_tasks: environment.yml

- include_tasks: setup-debian9.yml

- include_tasks: weechat.yml

- include_tasks: weechat_config.yml
  when: weechat_config_repo

- include_tasks: glowingbear.yml
  when: nginx_with_reverse_proxy

- include_tasks: services.yml
