---

- include_tasks: environment.yml

- include_tasks: setup-debian9.yml
  when: ansible_os_family == 'Debian' and ansible_distribution_version == '9'

- include_tasks: weechat.yml

- include_tasks: weechat_config.yml
  when: weechat_config_repo

- include_tasks: glowingbear.yml
  when: weechat_frontend

- name: Activate weechat service
  systemd:
    name: weechat
    enabled: true
    state: started

- include_tasks: nginx.yml
  when: nginx_with_reverse_proxy
