---
name: Molecule Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - debian9
          - ubuntu1804
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          sudo apt install docker
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          mv "${{ github.repository }}" andecy64.ircstack
          cd andecy64.ircstack
      - name: Test role against debian 9
        run: |
          molecule test
          molecule destroy
        env:
          MOLECULE_DISTRO: "${{ matrix.image }}"
